# Generated by Django 4.2 on 2023-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_discription_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_discription_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
